version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-crud-app
    restart: always
    ports:
      - "5005:5005"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      DB_DATABASE: service_db
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: >
      sh -c "until pg_isready -h postgres -p 5432; do sleep 2; done
      && npm run start:dev"
    networks:
      - nest-network

    volumes:
      postgres_data:
      node_modules:

    networks:
      nest-network:
      driver: bridge
